/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as ApiCronRefreshRouteImport } from './routes/api/cron/refresh'
import { Route as ApiPublicDiscoverSeasonsRouteImport } from './routes/api/public/discover-seasons'
import { Route as ApiPublicFetchTeamHistoryRouteImport } from './routes/api/public/fetch-team-history'
import { Route as ApiPublicSyncCompetitionsRouteImport } from './routes/api/public/sync-competitions'
import { Route as ApiPublicSyncFixturesDailyRouteImport } from './routes/api/public/sync-fixtures-daily'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'
import { Route as ApiPublicVerifyEndpointsRouteImport } from './routes/api/public/verify-endpoints'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshRoute = ApiCronRefreshRouteImport.update({
  id: '/api/cron/refresh',
  path: '/api/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscoverSeasonsRoute =
  ApiPublicDiscoverSeasonsRouteImport.update({
    id: '/api/public/discover-seasons',
    path: '/api/public/discover-seasons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFetchTeamHistoryRoute =
  ApiPublicFetchTeamHistoryRouteImport.update({
    id: '/api/public/fetch-team-history',
    path: '/api/public/fetch-team-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncCompetitionsRoute =
  ApiPublicSyncCompetitionsRouteImport.update({
    id: '/api/public/sync-competitions',
    path: '/api/public/sync-competitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncFixturesDailyRoute =
  ApiPublicSyncFixturesDailyRouteImport.update({
    id: '/api/public/sync-fixtures-daily',
    path: '/api/public/sync-fixtures-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyEndpointsRoute =
  ApiPublicVerifyEndpointsRouteImport.update({
    id: '/api/public/verify-endpoints',
    path: '/api/public/verify-endpoints',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/news'
    | '/settings'
    | '/match/$id'
    | '/api/cron/refresh'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/news'
    | '/settings'
    | '/match/$id'
    | '/api/cron/refresh'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/news'
    | '/settings'
    | '/match/$id'
    | '/api/cron/refresh'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  NewsRoute: typeof NewsRoute
  SettingsRoute: typeof SettingsRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiCronRefreshRoute: typeof ApiCronRefreshRoute
  ApiPublicDiscoverSeasonsRoute: typeof ApiPublicDiscoverSeasonsRoute
  ApiPublicFetchTeamHistoryRoute: typeof ApiPublicFetchTeamHistoryRoute
  ApiPublicSyncCompetitionsRoute: typeof ApiPublicSyncCompetitionsRoute
  ApiPublicSyncFixturesDailyRoute: typeof ApiPublicSyncFixturesDailyRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
  ApiPublicVerifyEndpointsRoute: typeof ApiPublicVerifyEndpointsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh': {
      id: '/api/cron/refresh'
      path: '/api/cron/refresh'
      fullPath: '/api/cron/refresh'
      preLoaderRoute: typeof ApiCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discover-seasons': {
      id: '/api/public/discover-seasons'
      path: '/api/public/discover-seasons'
      fullPath: '/api/public/discover-seasons'
      preLoaderRoute: typeof ApiPublicDiscoverSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-team-history': {
      id: '/api/public/fetch-team-history'
      path: '/api/public/fetch-team-history'
      fullPath: '/api/public/fetch-team-history'
      preLoaderRoute: typeof ApiPublicFetchTeamHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-competitions': {
      id: '/api/public/sync-competitions'
      path: '/api/public/sync-competitions'
      fullPath: '/api/public/sync-competitions'
      preLoaderRoute: typeof ApiPublicSyncCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-fixtures-daily': {
      id: '/api/public/sync-fixtures-daily'
      path: '/api/public/sync-fixtures-daily'
      fullPath: '/api/public/sync-fixtures-daily'
      preLoaderRoute: typeof ApiPublicSyncFixturesDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-endpoints': {
      id: '/api/public/verify-endpoints'
      path: '/api/public/verify-endpoints'
      fullPath: '/api/public/verify-endpoints'
      preLoaderRoute: typeof ApiPublicVerifyEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  NewsRoute: NewsRoute,
  SettingsRoute: SettingsRoute,
  MatchIdRoute: MatchIdRoute,
  ApiCronRefreshRoute: ApiCronRefreshRoute,
  ApiPublicDiscoverSeasonsRoute: ApiPublicDiscoverSeasonsRoute,
  ApiPublicFetchTeamHistoryRoute: ApiPublicFetchTeamHistoryRoute,
  ApiPublicSyncCompetitionsRoute: ApiPublicSyncCompetitionsRoute,
  ApiPublicSyncFixturesDailyRoute: ApiPublicSyncFixturesDailyRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
  ApiPublicVerifyEndpointsRoute: ApiPublicVerifyEndpointsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
