/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccuracyRouteImport } from './routes/_authenticated/accuracy'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMatchIdRouteImport } from './routes/_authenticated/match.$id'
import { Route as ApiCronRefreshRouteImport } from './routes/api/cron/refresh'
import { Route as ApiPublicComputeStandingsRouteImport } from './routes/api/public/compute-standings'
import { Route as ApiPublicDiscoverSeasonsRouteImport } from './routes/api/public/discover-seasons'
import { Route as ApiPublicFetchNewsRouteImport } from './routes/api/public/fetch-news'
import { Route as ApiPublicFetchPlayerPhotosRouteImport } from './routes/api/public/fetch-player-photos'
import { Route as ApiPublicFetchTeamHistoryRouteImport } from './routes/api/public/fetch-team-history'
import { Route as ApiPublicSyncCompetitionsRouteImport } from './routes/api/public/sync-competitions'
import { Route as ApiPublicSyncFixturesDailyRouteImport } from './routes/api/public/sync-fixtures-daily'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'
import { Route as ApiPublicVerifyEndpointsRouteImport } from './routes/api/public/verify-endpoints'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccuracyRoute = AuthenticatedAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchIdRoute = AuthenticatedMatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCronRefreshRoute = ApiCronRefreshRouteImport.update({
  id: '/api/cron/refresh',
  path: '/api/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicComputeStandingsRoute =
  ApiPublicComputeStandingsRouteImport.update({
    id: '/api/public/compute-standings',
    path: '/api/public/compute-standings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscoverSeasonsRoute =
  ApiPublicDiscoverSeasonsRouteImport.update({
    id: '/api/public/discover-seasons',
    path: '/api/public/discover-seasons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFetchNewsRoute = ApiPublicFetchNewsRouteImport.update({
  id: '/api/public/fetch-news',
  path: '/api/public/fetch-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFetchPlayerPhotosRoute =
  ApiPublicFetchPlayerPhotosRouteImport.update({
    id: '/api/public/fetch-player-photos',
    path: '/api/public/fetch-player-photos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFetchTeamHistoryRoute =
  ApiPublicFetchTeamHistoryRouteImport.update({
    id: '/api/public/fetch-team-history',
    path: '/api/public/fetch-team-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncCompetitionsRoute =
  ApiPublicSyncCompetitionsRouteImport.update({
    id: '/api/public/sync-competitions',
    path: '/api/public/sync-competitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncFixturesDailyRoute =
  ApiPublicSyncFixturesDailyRouteImport.update({
    id: '/api/public/sync-fixtures-daily',
    path: '/api/public/sync-fixtures-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyEndpointsRoute =
  ApiPublicVerifyEndpointsRouteImport.update({
    id: '/api/public/verify-endpoints',
    path: '/api/public/verify-endpoints',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accuracy': typeof AuthenticatedAccuracyRoute
  '/news': typeof AuthenticatedNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/compute-standings': typeof ApiPublicComputeStandingsRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-news': typeof ApiPublicFetchNewsRoute
  '/api/public/fetch-player-photos': typeof ApiPublicFetchPlayerPhotosRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accuracy': typeof AuthenticatedAccuracyRoute
  '/news': typeof AuthenticatedNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/compute-standings': typeof ApiPublicComputeStandingsRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-news': typeof ApiPublicFetchNewsRoute
  '/api/public/fetch-player-photos': typeof ApiPublicFetchPlayerPhotosRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/accuracy': typeof AuthenticatedAccuracyRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/cron/refresh': typeof ApiCronRefreshRoute
  '/api/public/compute-standings': typeof ApiPublicComputeStandingsRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
  '/api/public/fetch-news': typeof ApiPublicFetchNewsRoute
  '/api/public/fetch-player-photos': typeof ApiPublicFetchPlayerPhotosRoute
  '/api/public/fetch-team-history': typeof ApiPublicFetchTeamHistoryRoute
  '/api/public/sync-competitions': typeof ApiPublicSyncCompetitionsRoute
  '/api/public/sync-fixtures-daily': typeof ApiPublicSyncFixturesDailyRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/public/verify-endpoints': typeof ApiPublicVerifyEndpointsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/accuracy'
    | '/news'
    | '/settings'
    | '/match/$id'
    | '/api/cron/refresh'
    | '/api/public/compute-standings'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-news'
    | '/api/public/fetch-player-photos'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/accuracy'
    | '/news'
    | '/settings'
    | '/'
    | '/match/$id'
    | '/api/cron/refresh'
    | '/api/public/compute-standings'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-news'
    | '/api/public/fetch-player-photos'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/accuracy'
    | '/_authenticated/news'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/match/$id'
    | '/api/cron/refresh'
    | '/api/public/compute-standings'
    | '/api/public/discover-seasons'
    | '/api/public/fetch-news'
    | '/api/public/fetch-player-photos'
    | '/api/public/fetch-team-history'
    | '/api/public/sync-competitions'
    | '/api/public/sync-fixtures-daily'
    | '/api/public/tick'
    | '/api/public/verify-endpoints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCronRefreshRoute: typeof ApiCronRefreshRoute
  ApiPublicComputeStandingsRoute: typeof ApiPublicComputeStandingsRoute
  ApiPublicDiscoverSeasonsRoute: typeof ApiPublicDiscoverSeasonsRoute
  ApiPublicFetchNewsRoute: typeof ApiPublicFetchNewsRoute
  ApiPublicFetchPlayerPhotosRoute: typeof ApiPublicFetchPlayerPhotosRoute
  ApiPublicFetchTeamHistoryRoute: typeof ApiPublicFetchTeamHistoryRoute
  ApiPublicSyncCompetitionsRoute: typeof ApiPublicSyncCompetitionsRoute
  ApiPublicSyncFixturesDailyRoute: typeof ApiPublicSyncFixturesDailyRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
  ApiPublicVerifyEndpointsRoute: typeof ApiPublicVerifyEndpointsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accuracy': {
      id: '/_authenticated/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AuthenticatedAccuracyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$id': {
      id: '/_authenticated/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof AuthenticatedMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/refresh': {
      id: '/api/cron/refresh'
      path: '/api/cron/refresh'
      fullPath: '/api/cron/refresh'
      preLoaderRoute: typeof ApiCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/compute-standings': {
      id: '/api/public/compute-standings'
      path: '/api/public/compute-standings'
      fullPath: '/api/public/compute-standings'
      preLoaderRoute: typeof ApiPublicComputeStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discover-seasons': {
      id: '/api/public/discover-seasons'
      path: '/api/public/discover-seasons'
      fullPath: '/api/public/discover-seasons'
      preLoaderRoute: typeof ApiPublicDiscoverSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-news': {
      id: '/api/public/fetch-news'
      path: '/api/public/fetch-news'
      fullPath: '/api/public/fetch-news'
      preLoaderRoute: typeof ApiPublicFetchNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-player-photos': {
      id: '/api/public/fetch-player-photos'
      path: '/api/public/fetch-player-photos'
      fullPath: '/api/public/fetch-player-photos'
      preLoaderRoute: typeof ApiPublicFetchPlayerPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-team-history': {
      id: '/api/public/fetch-team-history'
      path: '/api/public/fetch-team-history'
      fullPath: '/api/public/fetch-team-history'
      preLoaderRoute: typeof ApiPublicFetchTeamHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-competitions': {
      id: '/api/public/sync-competitions'
      path: '/api/public/sync-competitions'
      fullPath: '/api/public/sync-competitions'
      preLoaderRoute: typeof ApiPublicSyncCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-fixtures-daily': {
      id: '/api/public/sync-fixtures-daily'
      path: '/api/public/sync-fixtures-daily'
      fullPath: '/api/public/sync-fixtures-daily'
      preLoaderRoute: typeof ApiPublicSyncFixturesDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-endpoints': {
      id: '/api/public/verify-endpoints'
      path: '/api/public/verify-endpoints'
      fullPath: '/api/public/verify-endpoints'
      preLoaderRoute: typeof ApiPublicVerifyEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccuracyRoute: typeof AuthenticatedAccuracyRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchIdRoute: typeof AuthenticatedMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccuracyRoute: AuthenticatedAccuracyRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchIdRoute: AuthenticatedMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCronRefreshRoute: ApiCronRefreshRoute,
  ApiPublicComputeStandingsRoute: ApiPublicComputeStandingsRoute,
  ApiPublicDiscoverSeasonsRoute: ApiPublicDiscoverSeasonsRoute,
  ApiPublicFetchNewsRoute: ApiPublicFetchNewsRoute,
  ApiPublicFetchPlayerPhotosRoute: ApiPublicFetchPlayerPhotosRoute,
  ApiPublicFetchTeamHistoryRoute: ApiPublicFetchTeamHistoryRoute,
  ApiPublicSyncCompetitionsRoute: ApiPublicSyncCompetitionsRoute,
  ApiPublicSyncFixturesDailyRoute: ApiPublicSyncFixturesDailyRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
  ApiPublicVerifyEndpointsRoute: ApiPublicVerifyEndpointsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
