/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as ApiPublicDiscoverSeasonsRouteImport } from './routes/api/public/discover-seasons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscoverSeasonsRoute =
  ApiPublicDiscoverSeasonsRouteImport.update({
    id: '/api/public/discover-seasons',
    path: '/api/public/discover-seasons',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/match/$id': typeof MatchIdRoute
  '/api/public/discover-seasons': typeof ApiPublicDiscoverSeasonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/news' | '/settings' | '/match/$id' | '/api/public/discover-seasons'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/news' | '/settings' | '/match/$id' | '/api/public/discover-seasons'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/settings'
    | '/match/$id'
    | '/api/public/discover-seasons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  SettingsRoute: typeof SettingsRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiPublicDiscoverSeasonsRoute: typeof ApiPublicDiscoverSeasonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discover-seasons': {
      id: '/api/public/discover-seasons'
      path: '/api/public/discover-seasons'
      fullPath: '/api/public/discover-seasons'
      preLoaderRoute: typeof ApiPublicDiscoverSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  SettingsRoute: SettingsRoute,
  MatchIdRoute: MatchIdRoute,
  ApiPublicDiscoverSeasonsRoute: ApiPublicDiscoverSeasonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
